defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: nikolaik/python-nodejs:python3.7-nodejs11

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-
      - run:
          name: Run install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dep-{{ checksum "package.json" }}

  testing:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-
      - run:
          name: Run tests
          command: npm run test

  linting:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-
      - run:
          name: Run ESLint
          command: npm run lint

  pre-build-staging:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-

      - run: apt-get update
      - run: apt-get -y install jq zip moreutils

      - run:
          name: Run semantic-release
          command: |
            npm i
            npm run semantic-release -- --branch ${CIRCLE_BRANCH} --dry-run
      - run: mkdir -p workspace

      - run: |
          cat .env > workspace/.env
          cat package.json > workspace/package.json
          cat src/manifest.json > workspace/manifest.json
      - persist_to_workspace:
          root: workspace
          paths:
            - .env
            - package.json
            - manifest.json

  build-staging:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-

      - run: apt-get update
      - run: apt-get -y install jq zip moreutils

      - run: cat workspace/.env >> $BASH_ENV
      - run: cat workspace/.env > .env
      - run: cat workspace/package.json > package.json
      - run: cat workspace/manifest.json > src/manifest.json

      - run: echo "REACT_APP_VERSION:" $REACT_APP_VERSION
      - run:
          name: Build project
          command: npm run build

      - run: mkdir -p workspace/build
      - run: cp -R colormate.sketchplugin  workspace/build

      - persist_to_workspace:
          root: workspace
          paths:
            - .env
            - build/

  zip-build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace
      - run: cat workspace/.env >> $BASH_ENV
      - run: apt-get update
      - run: apt-get -y install zip

      - run:
          name: Zipping project
          command: |
            echo "creating zip file:" colormate.zip
            cd workspace/build && zip -r ../../colormate.zip *
      - run: cp colormate.zip workspace/colormate.zip

      - persist_to_workspace:
          root: workspace
          paths:
            - .

  deploy-staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace
      - run: cat workspace/.env >> $BASH_ENV

      - run: apt-get update
      - run: apt-get -y install jq zip moreutils
      - run: pip install awscli

      - run:
          name: Deploy to S3
          command: aws s3 cp workspace/colormate.zip s3://colormate-testing/staging/

      - run:
          name: Notify slack channel
          command: |
            curl --header "Content-Type: application/json" --request POST --data \
            '{"text": "<'"$CIRCLE_BUILD_URL"'|#'"$CIRCLE_BUILD_NUM"'> New testing version deployed you can download it here: <'"$AWS_S3_URL_STAGING"/colormate_"$REACT_APP_VERSION".zip'|'colormate_"$REACT_APP_VERSION".zip'>"}' \
            $SLACK_WEBHOOK_URL
  pre-build-production:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-

      - run: apt-get update
      - run: apt-get -y install jq moreutils

      - run:
          name: Set next version in .env by using prepareRelease.sh
          command: |
            npm run semantic-release -- --dry-run
      - run:
          name: update env file
          command: |
            echo REACT_APP_GA_TRACKING_ID=$GA_TRACKING_ID >> .env
      - run:
          name: Prepare workspace
          command: |
            mkdir -p workspace
      - run:
          name: Save files to workspace
          command: |
            cat .env > workspace/.env
            cat package.json > workspace/package.json
            cat src/manifest.json > workspace/manifest.json
      - persist_to_workspace:
          root: workspace
          paths:
            - .

  build-production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-

      - run: apt-get update
      - run: apt-get -y install xmlstarlet

      - run: cat workspace/.env >> $BASH_ENV
      - run: cat workspace/.env > .env
      - run: cat workspace/package.json > package.json
      - run: cat workspace/manifest.json > src/manifest.json

      - run:
          name: Build project for version $REACT_APP_VERSION
          command: npm run build

      - run:
          name: Generate new appcast item
          command: bash ./updateAppcast.sh $REACT_APP_VERSION

      - run: mkdir -p workspace/build
      - run:
          name: Save build files to workspace
          command: |
            cat .appcast.xml > workspace/.appcast.xml
            cp -R colormate.sketchplugin  workspace/build
      - persist_to_workspace:
          root: workspace
          paths:
            - .

  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          keys:
            - v1-dep-{{ checksum "package.json" }}
            - v1-dep-

      - run: apt-get update
      - run: apt-get -y install jq moreutils

      - run:
          name: Setup Environment Variables
          command: |
            cat workspace/.env >> $BASH_ENV
            source $BASH_ENV
      - add_ssh_keys:
          fingerprints:
            - "14:80:8a:23:90:81:f4:28:16:ee:47:ef:14:ec:72:27"

      - run:
          name: Update .appcast.xml
          command: cat workspace/.appcast.xml > .appcast.xml

      - run:
          name: Update package.json
          command: cat workspace/package.json > package.json

      - run:
          name: Update manifest.json
          command: cat workspace/manifest.json > src/manifest.json

      - run:
          name: Commit files
          command: |
            echo """Host *
              StrictHostKeyChecking no""" >> ~/.ssh/config
            git config --global user.email "ci@circleci.com"
            git config --global user.name "Ci Server"
            git add .appcast.xml package.json src/manifest.json 
            git commit -m "New version released ${REACT_APP_VERSION} [ci skip]"   
            git push
            
      - run:
          name: Tag and release
          command: |
            npm i
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            npm run semantic-release
      - run:
          name: Notify slack channel
          command: |
            curl --header "Content-Type: application/json" --request POST --data \
            '{"text": "<'"$CIRCLE_BUILD_URL"'|#'"$CIRCLE_BUILD_NUM"'> :rocket: Colormate *v'"$REACT_APP_VERSION"'* deployed :rocket: \n Download it here <'"$AWS_S3_URL_PRODUCTION"/colormate_"$REACT_APP_VERSION".zip'|'colormate_"$REACT_APP_VERSION".zip'> "}' \
            $SLACK_WEBHOOK_URL
workflows:
  version: 2
  tagged-build:
    jobs:
      - install:
          filters:
            branches:
              only:
                - master
      - testing:
          filters:
            branches:
              only:
                - master
      - linting:
          filters:
            branches:
              only:
                - master
      - pre-build-production:
          requires:
            - install
            - testing
            - linting
          filters:
            branches:
              only:
                - master
      - build-production:
          requires:
            - pre-build-production
      - zip-build:
          requires:
            - build-production
      - deploy-production:
          requires:
            - zip-build

  deploy-staging:
    jobs:
      - install:
          filters:
            branches:
              only:
                - /release/.*/
      - testing:
          filters:
            branches:
              only:
                - /release/.*/
      - linting:
          filters:
            branches:
              only:
                - /release/.*/
      - pre-build-staging:
          requires:
            - install
            - testing
            - linting
          filters:
            branches:
              only:
                - /release/.*/
      - build-staging:
          requires:
            - pre-build-staging
      - zip-build:
          requires:
            - build-staging
      - deploy-staging:
          requires:
            - zip-build